console.sh needs to be symlinked, not copied
The console.sh needs to be symlinked, not copied. If you copy it, you will get an error when trying to run it:

    $ orientdb
    Error: Could not find or load main class com.orientechnologies.orient.graph.console.OGremlinConsole